import { supabase } from '@/lib/supabaseClient';
import { CategoryTemplateService } from '../services/categoryTemplateService';

/**
 * Утилита для обновления системы спецификаций
 */
export class SpecificationUpdater {
  
  /**
   * Полное обновление шаблонов спецификаций
   */
  static async updateAllTemplates() {
    console.log('🔧 Updating specification templates...');
    
    try {
      // 1. Удаляем старые шаблоны для GPU
      await this.cleanupGpuTemplates();
      
      // 2. Создаем новые шаблоны
      await CategoryTemplateService.initializeCategoryTemplates();
      
      // 3. Обновляем auto_generated_specs в categories
      await this.updateAutoGeneratedSpecs();
      
      console.log('✅ All templates updated successfully!');
      return { success: true };
      
    } catch (error) {
      console.error('❌ Failed to update templates:', error);
      return { success: false, error };
    }
  }
  
  /**
   * Очистка старых шаблонов GPU
   */
  private static async cleanupGpuTemplates() {
    console.log('🧹 Cleaning up old GPU templates...');
    
    // Получаем ID категории видеокарт
    const { data: gpuCategory } = await supabase
      .from('categories')
      .select('id')
      .eq('slug', 'graphics-cards')
      .single();
      
    if (!gpuCategory) {
      throw new Error('GPU category not found');
    }
    
    // Удаляем старое поле power_consumption
    const { error } = await supabase
      .from('category_specification_templates')
      .delete()
      .eq('category_id', gpuCategory.id)
      .eq('name', 'power_consumption');
      
    if (error) {
      console.error('Error deleting old power_consumption template:', error);
    } else {
      console.log('✅ Old power_consumption template removed');
    }
  }
  
  /**
   * Обновление auto_generated_specs в таблице categories
   */
  private static async updateAutoGeneratedSpecs() {
    console.log('📝 Updating auto_generated_specs...');
    
    // Получаем все PC категории
    const { data: categories } = await supabase
      .from('categories')
      .select('id, slug')
      .eq('is_pc_component', true);
      
    if (!categories) return;
    
    for (const category of categories) {
      try {
        // Получаем шаблоны для категории
        const templates = await CategoryTemplateService.getTemplatesForCategory(category.slug);
        
        // Конвертируем в формат auto_generated_specs
        const autoGeneratedSpecs = templates.map(template => ({
          name: template.name,
          displayName: template.display_name,
          dataType: template.data_type,
          isRequired: template.is_required,
          isCompatibilityKey: template.is_compatibility_key,
          displayOrder: template.display_order,
          units: template.units,
          minValue: template.min_value,
          maxValue: template.max_value,
          enumValues: template.enum_values,
        }));
        
        // Обновляем auto_generated_specs
        const { error } = await supabase
          .from('categories')
          .update({ 
            auto_generated_specs: autoGeneratedSpecs,
            smart_detection_enabled: true,
            last_profile_detection: new Date().toISOString()
          })
          .eq('id', category.id);
          
        if (error) {
          console.error(`Error updating ${category.slug}:`, error);
        } else {
          console.log(`✅ Updated auto_generated_specs for ${category.slug}`);
        }
        
      } catch (error) {
        console.error(`Error processing ${category.slug}:`, error);
      }
    }
  }
  
  /**
   * Быстрое обновление только GPU спецификаций
   */
  static async updateGpuSpecsOnly() {
    console.log('🎮 Updating GPU specifications only...');
    
    try {
      // Очищаем старые шаблоны GPU
      await this.cleanupGpuTemplates();
      
      // Создаем новые шаблоны (включая GPU)
      await CategoryTemplateService.initializeCategoryTemplates();
      
      // Обновляем auto_generated_specs для GPU
      const { data: gpuCategory } = await supabase
        .from('categories')
        .select('id')
        .eq('slug', 'graphics-cards')
        .single();
        
      if (gpuCategory) {
        const templates = await CategoryTemplateService.getTemplatesForCategory('graphics-cards');
        const autoGeneratedSpecs = templates.map(template => ({
          name: template.name,
          displayName: template.display_name,
          dataType: template.data_type,
          isRequired: template.is_required,
          isCompatibilityKey: template.is_compatibility_key,
          displayOrder: template.display_order,
          units: template.units,
          minValue: template.min_value,
          maxValue: template.max_value,
        }));
        
        await supabase
          .from('categories')
          .update({ auto_generated_specs: autoGeneratedSpecs })
          .eq('id', gpuCategory.id);
      }
      
      console.log('✅ GPU specifications updated successfully!');
      return { success: true };
      
    } catch (error) {
      console.error('❌ Failed to update GPU specs:', error);
      return { success: false, error };
    }
  }
}