import { CreateSpecificationTemplate } from './types';

/**
 * Hardcoded specification templates for product categories
 * This is a centralized place for managing all specifications
 */

// CPU Templates
export const CPU_TEMPLATES: Omit<CreateSpecificationTemplate, 'category_id'>[] = [
  {
    name: 'manufacturer',
    display_name: 'Processor Manufacturer',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 1,
    enum_values: ['Intel', 'AMD', 'Apple', 'Qualcomm', 'MediaTek'],
    help_text: 'CPU manufacturer',
  },
  {
    name: 'socket',
    display_name: 'Processor Socket',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 2,
    enum_values: ['AM4', 'AM5', 'LGA1700', 'LGA1200', 'LGA1151', 'LGA2066', 'TR4', 'sTRX4'],
    help_text: 'Socket type for motherboard installation',
  },
  {
    name: 'cores',
    display_name: 'Processor Core',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 3,
    help_text: 'Number of physical cores',
  },
  {
    name: 'threads',
    display_name: 'Processor Threads',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 4,
    help_text: 'Number of logical threads',
  },
  {
    name: 'base_clock',
    display_name: 'Clock Speed',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 5,
    unit: 'GHz',
    help_text: 'Base clock frequency',
  },
  {
    name: 'boost_clock',
    display_name: 'Overclocking Speed',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 6,
    unit: 'GHz',
    help_text: 'Maximum boost clock frequency',
  },
  {
    name: 'l2_cache',
    display_name: 'L2 Cache',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 7,
    unit: 'MB',
    help_text: 'Level 2 cache size',
  },
  {
    name: 'l3_cache',
    display_name: 'L3 Cache',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 8,
    unit: 'MB',
    help_text: 'Level 3 cache size',
  },
  {
    name: 'bit_processing',
    display_name: '64-bit Processing',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 9,
    help_text: 'Supports 64-bit processing',
  },
  {
    name: 'process_technology',
    display_name: 'Process Technology',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 10,
    enum_values: ['5nm', '7nm', '10nm', '12nm', '14nm', '16nm', '22nm', '28nm'],
    unit: 'nm',
    help_text: 'Manufacturing process technology',
  },
  {
    name: 'graphics_controller',
    display_name: 'Graphics Controller Model',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 11,
    help_text: 'Integrated graphics controller model',
  },
  {
    name: 'integrated_graphics',
    display_name: 'Integrated Graphics',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 12,
    help_text: 'Has integrated graphics',
  },
  {
    name: 'tdp',
    display_name: 'Thermal Design Power',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 13,
    unit: 'W',
    help_text: 'Thermal Design Power',
  },
  {
    name: 'thermal_specification',
    display_name: 'Thermal Specification',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 14,
    unit: '°C',
    help_text: 'Maximum operating temperature',
  },
];

// GPU Templates
export const GPU_TEMPLATES: Omit<CreateSpecificationTemplate, 'category_id'>[] = [
  {
    name: 'chipset_manufacturer',
    display_name: 'Chipset Manufacturer',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 1,
    enum_values: ['NVIDIA', 'AMD', 'Intel'],
    help_text: 'GPU chipset manufacturer',
  },
  {
    name: 'chipset_line',
    display_name: 'Chipset Line',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 2,
    enum_values: ['GeForce', 'Radeon', 'Arc', 'Quadro', 'Tesla'],
    help_text: 'GPU chipset product line',
  },
  {
    name: 'chipset_series',
    display_name: 'Chipset Series',
    data_type: 'text',
    is_required: false,
    is_filter: true,
    display_order: 3,
    help_text: 'GPU chipset series',
  },
  {
    name: 'chipset_model',
    display_name: 'Chipset Model',
    data_type: 'text',
    is_required: true,
    is_filter: true,
    display_order: 4,
    help_text: 'GPU chipset model',
  },
  {
    name: 'standard_memory',
    display_name: 'Standard Memory',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 5,
    unit: 'GB',
    help_text: 'Video memory size',
  },
  {
    name: 'memory_technology',
    display_name: 'Memory Technology',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 6,
    enum_values: ['GDDR6', 'GDDR6X', 'GDDR5', 'HBM2', 'HBM3'],
    help_text: 'Video memory technology',
  },
  {
    name: 'bus_width',
    display_name: 'Bus Width',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 7,
    unit: 'bit',
    help_text: 'Memory bus width',
  },
  {
    name: 'gpu_boost_clock',
    display_name: 'GPU Boost Clock',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 8,
    unit: 'MHz',
    help_text: 'GPU boost clock frequency',
  },
  {
    name: 'cuda_cores',
    display_name: 'CUDA Cores',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 9,
    help_text: 'Number of CUDA cores (NVIDIA)',
  },
  {
    name: 'ai_powered',
    display_name: 'AI-powered',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 10,
    help_text: 'Supports AI acceleration',
  },
  {
    name: 'api_supported',
    display_name: 'API Supported',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 11,
    help_text: 'Supported graphics APIs',
  },
  {
    name: 'monitors_supported',
    display_name: 'Number of Monitors Supported',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 12,
    help_text: 'Maximum number of monitors supported',
  },
  {
    name: 'max_resolution',
    display_name: 'Maximum Digital Display Resolution',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 13,
    help_text: 'Maximum supported resolution',
  },
  {
    name: 'features',
    display_name: 'Features',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 14,
    help_text: 'Special features and technologies',
  },
  {
    name: 'host_interface',
    display_name: 'Host Interface',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 15,
    enum_values: ['PCIe 4.0 x16', 'PCIe 3.0 x16', 'PCIe 5.0 x16'],
    help_text: 'Host system interface',
  },
  {
    name: 'displayport',
    display_name: 'DisplayPort',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 16,
    help_text: 'Has DisplayPort output',
  },
  {
    name: 'displayport_outputs',
    display_name: 'Number of DisplayPort Outputs',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 17,
    help_text: 'Number of DisplayPort outputs',
  },
  {
    name: 'hdmi',
    display_name: 'HDMI',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 18,
    help_text: 'Has HDMI output',
  },
  {
    name: 'hdmi_outputs',
    display_name: 'Number of HDMI Outputs',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 19,
    help_text: 'Number of HDMI outputs',
  },
  {
    name: 'power_wattage',
    display_name: 'Power Supply Wattage',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 20,
    unit: 'W',
    help_text: 'Required power supply wattage',
  },
  {
    name: 'power_connector',
    display_name: 'Power Connector',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 21,
    enum_values: ['6-pin', '8-pin', '6+8-pin', '8+8-pin', '12VHPWR', 'None'],
    help_text: 'Power connector type',
  },
  {
    name: 'slot_space',
    display_name: 'Slot Space Required',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 22,
    help_text: 'Number of expansion slots required',
  },
  {
    name: 'form_factor',
    display_name: 'Form Factor',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 23,
    enum_values: ['Full Height', 'Low Profile', 'Mini-ITX', 'Dual Slot', 'Triple Slot'],
    help_text: 'Card form factor',
  },
  {
    name: 'cooler_type',
    display_name: 'Cooler Type',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 24,
    enum_values: ['Air', 'Liquid', 'Hybrid', 'Passive'],
    help_text: 'Cooling system type',
  },
  {
    name: 'height',
    display_name: 'Height',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 25,
    unit: 'mm',
    help_text: 'Card height',
  },
  {
    name: 'width',
    display_name: 'Width',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 26,
    unit: 'mm',
    help_text: 'Card width',
  },
  {
    name: 'length',
    display_name: 'Length',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 27,
    unit: 'mm',
    help_text: 'Card length',
  },
];

// RAM Templates
export const RAM_TEMPLATES: Omit<CreateSpecificationTemplate, 'category_id'>[] = [
  {
    name: 'memory_size',
    display_name: 'Memory Size',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 1,
    unit: 'GB',
    help_text: 'Memory capacity',
  },
  {
    name: 'memory_technology',
    display_name: 'Memory Technology',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 2,
    enum_values: ['DDR4', 'DDR5', 'DDR3', 'DDR2'],
    help_text: 'Memory technology type',
  },
  {
    name: 'memory_voltage',
    display_name: 'Memory Voltage',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 3,
    unit: 'V',
    help_text: 'Operating voltage',
  },
  {
    name: 'number_of_modules',
    display_name: 'Number of Modules',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 4,
    help_text: 'Number of memory modules in kit',
  },
  {
    name: 'memory_speed',
    display_name: 'Memory Speed',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 5,
    unit: 'MHz',
    help_text: 'Memory speed frequency',
  },
  {
    name: 'memory_standard',
    display_name: 'Memory Standard',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 6,
    enum_values: ['JEDEC', 'XMP', 'DOCP', 'AMP'],
    help_text: 'Memory standard specification',
  },
  {
    name: 'memory_rank',
    display_name: 'Memory Rank',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 7,
    enum_values: ['Single Rank', 'Dual Rank', 'Quad Rank'],
    help_text: 'Memory rank configuration',
  },
  {
    name: 'cas_latency',
    display_name: 'CAS Latency',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 8,
    help_text: 'Column Address Strobe latency',
  },
  {
    name: 'number_of_pins',
    display_name: 'Number of Pins',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 9,
    enum_values: ['288-pin', '260-pin', '204-pin', '240-pin'],
    help_text: 'Number of connector pins',
  },
  {
    name: 'form_factor',
    display_name: 'Form Factor',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 10,
    enum_values: ['DIMM', 'SO-DIMM', 'Micro-DIMM', 'Mini-DIMM'],
    help_text: 'Memory module form factor',
  },
  {
    name: 'thickness',
    display_name: 'Thickness',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 11,
    unit: 'mil',
    help_text: 'Module thickness',
  },
  {
    name: 'width',
    display_name: 'Width',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 12,
    unit: 'mm',
    help_text: 'Module width',
  },
  {
    name: 'length',
    display_name: 'Length',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 13,
    unit: 'mm',
    help_text: 'Module length',
  },
];

// Motherboard Templates
export const MOTHERBOARD_TEMPLATES: Omit<CreateSpecificationTemplate, 'category_id'>[] = [
  {
    name: 'chipset_manufacturer',
    display_name: 'Chipset Manufacturer',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 1,
    enum_values: ['Intel', 'AMD', 'NVIDIA'],
    help_text: 'Motherboard chipset manufacturer',
  },
  {
    name: 'chipset_model',
    display_name: 'Chipset Model',
    data_type: 'text',
    is_required: true,
    is_filter: true,
    display_order: 2,
    help_text: 'Motherboard chipset model',
  },
  {
    name: 'total_processors_supported',
    display_name: 'Total Processor Supported',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 3,
    help_text: 'Maximum number of processors supported',
  },
  {
    name: 'processor_socket',
    display_name: 'Processor Socket',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 4,
    enum_values: ['AM4', 'AM5', 'LGA1700', 'LGA1200', 'LGA1151', 'LGA2066', 'TR4', 'sTRX4'],
    help_text: 'Supported processor socket type',
  },
  {
    name: 'processors_supported',
    display_name: 'Processors Supported',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 5,
    help_text: 'List of supported processor models',
  },
  {
    name: 'memory_slots',
    display_name: 'Number of Memory Slots',
    data_type: 'number',
    is_required: true,
    is_filter: true,
    display_order: 6,
    help_text: 'Number of memory slots',
  },
  {
    name: 'memory_form_factor',
    display_name: 'Memory Form Factor',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 7,
    enum_values: ['DIMM', 'SO-DIMM'],
    help_text: 'Supported memory form factor',
  },
  {
    name: 'max_memory_supported',
    display_name: 'Maximum Memory Supported',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 8,
    unit: 'GB',
    help_text: 'Maximum supported memory capacity',
  },
  {
    name: 'memory_technology',
    display_name: 'Memory Technology',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 9,
    enum_values: ['DDR4', 'DDR5', 'DDR3'],
    help_text: 'Supported memory technology',
  },
  {
    name: 'memory_speed_supported',
    display_name: 'Memory Speed Supported',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 10,
    help_text: 'Supported memory speeds',
  },
  {
    name: 'controller_type',
    display_name: 'Controller Type',
    data_type: 'text',
    is_required: false,
    is_filter: true,
    display_order: 11,
    help_text: 'Storage controller type',
  },
  {
    name: 'raid_supported',
    display_name: 'RAID Supported',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 12,
    help_text: 'Supports RAID configuration',
  },
  {
    name: 'raid_levels',
    display_name: 'RAID Levels',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 13,
    help_text: 'Supported RAID levels',
  },
  {
    name: 'onboard_video',
    display_name: 'Onboard Video',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 14,
    help_text: 'Has onboard video output',
  },
  {
    name: 'graphics_controller_model',
    display_name: 'Graphics Controller Model',
    data_type: 'text',
    is_required: false,
    is_filter: false,
    display_order: 15,
    help_text: 'Onboard graphics controller model',
  },
  {
    name: 'audio_channels',
    display_name: 'Audio Channels',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 16,
    enum_values: ['2.1', '5.1', '7.1', 'None'],
    help_text: 'Audio channel configuration',
  },
  {
    name: 'gigabit_ethernet',
    display_name: 'Gigabit Ethernet',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 17,
    help_text: 'Has Gigabit Ethernet port',
  },
  {
    name: 'pcie_standard',
    display_name: 'PCI Express Standard',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 18,
    enum_values: ['PCIe 3.0', 'PCIe 4.0', 'PCIe 5.0'],
    help_text: 'PCI Express standard version',
  },
  {
    name: 'total_pcie_slots',
    display_name: 'Total Number of PCI Express Slots',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 19,
    help_text: 'Total number of PCIe slots',
  },
  {
    name: 'pcie_x16_slots',
    display_name: 'Number of PCI Express x16 Slots',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 20,
    help_text: 'Number of PCIe x16 slots',
  },
  {
    name: 'total_usb_ports',
    display_name: 'Total Number of USB Ports',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 21,
    help_text: 'Total number of USB ports',
  },
  {
    name: 'usb_2_ports',
    display_name: 'Number of USB 2.0 Ports',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 22,
    help_text: 'Number of USB 2.0 ports',
  },
  {
    name: 'usb_3_gen1_ports',
    display_name: 'Number of USB 3.2 Gen 1 Type-A Ports',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 23,
    help_text: 'Number of USB 3.2 Gen 1 Type-A ports',
  },
  {
    name: 'vga',
    display_name: 'VGA',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 24,
    help_text: 'Has VGA output',
  },
  {
    name: 'hdmi',
    display_name: 'HDMI',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 25,
    help_text: 'Has HDMI output',
  },
  {
    name: 'hdmi_version',
    display_name: 'HDMI Version',
    data_type: 'enum',
    is_required: false,
    is_filter: true,
    display_order: 26,
    enum_values: ['HDMI 1.4', 'HDMI 2.0', 'HDMI 2.1'],
    help_text: 'HDMI version supported',
  },
  {
    name: 'displayport',
    display_name: 'DisplayPort',
    data_type: 'boolean',
    is_required: false,
    is_filter: true,
    display_order: 27,
    help_text: 'Has DisplayPort output',
  },
  {
    name: 'network_rj45_ports',
    display_name: 'Number of Network (RJ-45) Ports',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 28,
    help_text: 'Number of RJ-45 network ports',
  },
  {
    name: 'm2_interfaces',
    display_name: 'Number of M.2 Interfaces',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 29,
    help_text: 'Number of M.2 interfaces',
  },
  {
    name: 'onboard_usb_ports',
    display_name: 'Total Number of Onboard USB Ports',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 30,
    help_text: 'Total number of onboard USB ports',
  },
  {
    name: 'onboard_usb_2_ports',
    display_name: 'Number of Onboard USB 2.0 Ports',
    data_type: 'number',
    is_required: false,
    is_filter: true,
    display_order: 31,
    help_text: 'Number of onboard USB 2.0 ports',
  },
  {
    name: 'form_factor',
    display_name: 'Form Factor',
    data_type: 'enum',
    is_required: true,
    is_filter: true,
    display_order: 32,
    enum_values: ['ATX', 'Micro-ATX', 'Mini-ITX', 'E-ATX', 'XL-ATX'],
    help_text: 'Motherboard form factor',
  },
  {
    name: 'width',
    display_name: 'Width',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 33,
    unit: 'mm',
    help_text: 'Motherboard width',
  },
  {
    name: 'depth',
    display_name: 'Depth',
    data_type: 'number',
    is_required: false,
    is_filter: false,
    display_order: 34,
    unit: 'mm',
    help_text: 'Motherboard depth',
  },
];

// Primary category templates (for dropdown display)
const PRIMARY_CATEGORY_TEMPLATES: Record<
  string,
  Omit<CreateSpecificationTemplate, 'category_id'>[]
> = {
  cpu: CPU_TEMPLATES,
  gpu: GPU_TEMPLATES,
  ram: RAM_TEMPLATES,
  motherboard: MOTHERBOARD_TEMPLATES,
};

// Category slug to templates mapping (includes aliases for backward compatibility)
const CATEGORY_TEMPLATES: Record<string, Omit<CreateSpecificationTemplate, 'category_id'>[]> = {
  cpu: CPU_TEMPLATES,
  processors: CPU_TEMPLATES,
  gpu: GPU_TEMPLATES,
  'graphics-cards': GPU_TEMPLATES,
  ram: RAM_TEMPLATES,
  memory: RAM_TEMPLATES,
  motherboard: MOTHERBOARD_TEMPLATES,
  motherboards: MOTHERBOARD_TEMPLATES,
  mainboard: MOTHERBOARD_TEMPLATES,
  mainboards: MOTHERBOARD_TEMPLATES,
};

/**
 * Get templates for a specific category slug
 */
export function getTemplatesForCategorySlug(
  categorySlug: string
): Omit<CreateSpecificationTemplate, 'category_id'>[] | null {
  return CATEGORY_TEMPLATES[categorySlug] || null;
}

/**
 * Check if templates exist for a category
 */
export function hasTemplatesForCategory(categorySlug: string): boolean {
  return categorySlug in CATEGORY_TEMPLATES;
}

/**
 * Get all available category slugs that have templates (only primary categories for UI)
 */
export function getAvailableCategorySlugs(): string[] {
  return Object.keys(PRIMARY_CATEGORY_TEMPLATES);
}

/**
 * Get all templates for all categories
 */
export function getAllCategoryTemplates(): Record<
  string,
  Omit<CreateSpecificationTemplate, 'category_id'>[]
> {
  return CATEGORY_TEMPLATES;
}
